### ISSUE TITLE
Maximum cell number supported

### ISSUE THREAD

**Issue by Beiusxzw** [SchubertLab/mvTCR#22]
I am wondering about the maximum cell number supported by mvTCR, as my 256 GB machine fails to run the pipeline for over 1 million T cells when executing `mvtcr.models.model_selection.run_model_selection`. The error traceback is as follows:

![image](https://github.com/user-attachments/assets/46f45eae-d709-4d89-96d4-e2338ee31482)

**Comment by afonsoguerra** [comment]
I think you answered your own question... if you had a 1TB+ RAM on your machine that analysis would have likely been fine, it says at the bottom you would have needed 818GB RAM to store that particular array.

**Comment by ArcaneEmergence** [comment]
Hi Beiusxzw, thank you for using mvTCR and addressing this issue. I have pushed a new version, which should improve the efficiency of the conversion from sparse to dense array. Could you try this out and let me know if this works for you? Alternatively, you can also change the evaluation function to one which doesn't need a pairwise connectivity matrix.

**Comment by Beiusxzw** [comment]
Thanks for timely response! I have pulled the updated version and it worked well with my data.
