### ISSUE TITLE
Questions about dependency versions provided in requirements.txt

### ISSUE THREAD

**Issue by gwentea** [SchubertLab/mvTCR#3]
Dear Authors,

Thanks for the great work.

I was able to install mvTCR and run your tutorials in a conda environment, but encountered several problems which I suppose were caused by differences in dependency versions.

With scirpy=0.6.1, I ran into errors when running the following scripts as ir.pp.merge_with_ir(adata, adata_tcr) did not create the `IR_VDJ_1_junction_aa` information in adata.obs when merging the TCR and RNA data
notebook: /mvTCR/tutorials/01_preprocessing.ipynb
```
adata = adata[~adata.obs['IR_VDJ_1_junction_aa'].isna()]
adata = adata[~adata.obs['IR_VJ_1_junction_aa'].isna()].copy()
```
Switching to scirpy=0.7.0 resolved this issue.

Another problem was caused by optuna. `optuna.structs` is removed in optuna=3.0.3 (which was automatically installed since the version was not provided), and I haven't been able to locate the correct version of optuna...
Could you please provide the specific optuna version that was used?

Thanks for you time!

**Comment by drEast** [comment]
Hi,
Thanks for your interest in our tools.
I updated the requirement file for a scirpy version >=0.7 and the optuna versions 2.10.1, which we used for our tests.
This will hopefully resolve your issue.
Thanks and best,
Felix
