### ISSUE TITLE
while downloading the datasets in tutorials, page not found

### ISSUE THREAD

**Issue by YufanXia999** [SchubertLab/mvTCR#5]
Dear authors,

thank you for your work! But the second link "https://www.ebi.ac.uk/arrayexpress/files/E-MTAB-10026/E-MTAB-10026.processed.2.zip" in the 01_preprocessing notebook file from tutorials folder will return PAGE NOT FOUND. I will appreciate if the link can be updated but it is not urgent. 

Thank you for your time!

**Comment by drEast** [comment]
Hi,
Thanks for pointing this out. 
The path to the data repository changed and, therefore, was outdated. I updated it accordingly.
Please let me know, if there still occure problems.
Best,
Felix
