### ISSUE TITLE
might need to upgrade anndata in requirement.txt

### ISSUE THREAD

**Issue by YufanXia999** [SchubertLab/mvTCR#6]
Dear Felix,

me and some colleges of mine have problem while loading the dataset using sc.read_h5ad() function. The error messages are different, e.g. in my computer, it shows KeyError: 'dict'. For one of my colleges, it shows AttributeError: 'Dataset' object has no attribute 'asstr'. But regardless of what error it shows, all can be solved after upgrading anndata to the newest version 0.8.0. It is not the problem of mvTCR, but the dataset cannot be loaded properly otherwise. If you have some other options to solve this dataset load error, I am happy to try them. 

Thank you very much for your work and time!
Yufan

**Comment by drEast** [comment]
Thanks for pointing this out. I updated the requirements.
