### ISSUE TITLE
testing the second tutorial notebook: training_analysis.ipynb

### ISSUE THREAD

**Issue by mbensouda** [SchubertLab/mvTCR#8]
Thank you so much in advance for your help. I have encountered the following regarding optuna when running the 
run_model_selection() when calling the training functions in the notebook: 
` ---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[8], line 6
      4 n_samples = 3
      5 n_gpus = 1
----> 6 run_model_selection(adata, params_experiment, params_optimization, n_samples, timeout, n_gpus)

File ~/TCR_data/mvTCR/tcr_embedding/models/model_selection.py:135, in run_model_selection(adata, params_experiment, params_optimization, num_samples, timeout, n_jobs)
    132     os.remove(params_experiment['save_path'] + '.db')
    133 os.makedirs(os.path.dirname(params_experiment['save_path']), exist_ok=True)
--> 135 study = optuna.create_study(study_name=params_experiment['study_name'], sampler=sampler, storage=storage,
    136                             direction=direction, load_if_exists=False)
    138 suggest_params = get_parameter_functions(params_experiment['model_name'], params_optimization['name'])
    139 # study.enqueue_trial(init_params)

File /share/mbensouda/miniconda3/envs/mvTCR/lib/python3.8/site-packages/optuna/study/study.py:1136, in create_study(storage, sampler, pruner, study_name, direction, load_if_exists, directions)
   1127     raise ValueError(
   1128         "Please set either 'minimize' or 'maximize' to direction. You can also set the "
   1129         "corresponding `StudyDirection` member."
   1130     )
   1132 direction_objects = [
   1133     d if isinstance(d, StudyDirection) else StudyDirection[d.upper()] for d in directions
   1134 ]
-> 1136 storage = storages.get_storage(storage)
   1137 try:
   1138     study_id = storage.create_new_study(study_name)

File /share/mbensouda/miniconda3/envs/mvTCR/lib/python3.8/site-packages/optuna/storages/__init__.py:31, in get_storage(storage)
     29         return RedisStorage(storage)
     30     else:
---> 31         return _CachedStorage(RDBStorage(storage))
     32 elif isinstance(storage, RDBStorage):
     33     return _CachedStorage(storage)

File /share/mbensouda/miniconda3/envs/mvTCR/lib/python3.8/site-packages/optuna/storages/_rdb/storage.py:187, in RDBStorage.__init__(self, url, engine_kwargs, skip_compatibility_check, heartbeat_interval, grace_period, failed_trial_callback)
    185 self._version_manager = _VersionManager(self.url, self.engine, self.scoped_session)
    186 if not skip_compatibility_check:
--> 187     self._version_manager.check_table_schema_compatibility()

File /share/mbensouda/miniconda3/envs/mvTCR/lib/python3.8/site-packages/optuna/storages/_rdb/storage.py:1310, in _VersionManager.check_table_schema_compatibility(self)
   1306 version_info = models.VersionInfoModel.find(session)
   1308 assert version_info is not None
-> 1310 current_version = self.get_current_version()
   1311 head_version = self.get_head_version()
   1312 if current_version == head_version:

File /share/mbensouda/miniconda3/envs/mvTCR/lib/python3.8/site-packages/optuna/storages/_rdb/storage.py:1337, in _VersionManager.get_current_version(self)
   1335 context = alembic.migration.MigrationContext.configure(self.engine.connect())
   1336 version = context.get_current_revision()
-> 1337 assert version is not None
   1339 return version

AssertionError: `

Thank you so much for your answer!

**Comment by drEast** [comment]
This is a dependency issue of optuna in combination with sqlalchemy. 
A quick fix should be to manually downgrade to optuna==2.10.1 and sqlalchemy==1.4.26
Please let me know, if the problem continues.

We are currently working on updating the requirements in the repo and the repairing the pip installable version, which should follow in the next weeks.
